create table final_project.owner_files
(
    id            integer generated by default as identity
        primary key,
    owner_id      integer
        constraint owner_files_users_user_id_fk
            references final_project.users,
    file_name     varchar,
    type          varchar,
    file_data     oid,
    restaurant_id integer
        constraint uk_ig7p0db6bqehj5s0wnhfyddh3
            unique
        constraint fk7e5eq9xwh7txiv0smxowvy9bc
            references final_project.restaurants
);

alter table final_project.owner_files
    owner to postgres;
