
create table final_project.owner_restaurant
(
    id            integer generated by default as identity
        constraint owner_restaurant_pk
            primary key,
    owner_id      integer
        constraint owner_restaurant_users_user_id_fk
            references final_project.users,
    restaurant_id integer
        constraint owner_restaurant_restaurants_restaurant_id_fk
            references final_project.restaurants
);

alter table final_project.owner_restaurant
    owner to postgres;

