spring:
  application:
    name: WoltProject
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rebbin12
  liquibase:
    change-log: liquibase/changelog-master.yaml
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update

  app:
    security:
      jwt:
        expiration: 86400000

  jwt_k:
    key: QmFzZTY0IGVuY29kaW5nIHNjaGVtZXMgYXJlIGNvbW1vbmx5IHVzZWQgd2hlbiB0aGVyZSBpcyBhIG5lZWQgdG8gZW5jb2RlIGJpbmFyeSBkYXRhLCBlc3BlY2lhbGx5IHdoZW4gdGhhdCBkYXRhIG5lZWRzIHRvIGJlIHN0b3JlZCBhbmQgdHJhbnNmZXJyZWQgb3ZlciBtZWRpYSB0aGF0IGFyZSBkZXNpZ25lZCB0byBkZWFsIHdpdGggdGV4dC4gVGhpcyBlbmNvZGluZyBoZWxwcyB0byBlbnN1cmUgdGhhdCB0aGUgZGF0YSByZW1haW5zIGludGFjdCB3aXRob3V0IG1vZGlmaWNhdGlvbiBkdXJpbmcgdHJhbnNwb3J0LiBCYXNlNjQgaXMgdXNlZCBjb21tb25seSBpbiBhIG51bWJlciBvZiBhcHBsaWNhdGlvbnMgaW5jbHVkaW5nIGVtYWlsIHZpYSBNSU1FLCBhcyB3ZWxsIGFzIHN0b3JpbmcgY29tcGxleCBkYXRh

  mail:
    host: smtp.gmail.com
    port: 587
    username: oyunefsanesi420@gmail.com
    password: awxdpsajmbstivat
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          mime:
            charset: UTF

